language: node_js
addons:
    chrome: stable
cache: yarn
node_js:
    - "9"
before_script:
    - yarn config set registry http://registry.npm.taobao.org/
script:
    - yarn test
after_script:
    - yarn coverage
brabches:
    only:
        - master
