language: node_js
cache: yarn
node_js:
    - "9"
script:
    - yarn config set registry http://registry.npm.taobao.org/
    - yarn test
after_script:
    - yarn coverage
brabches:
    only:
        - master
